<?php
// *** autogenerated preset file 
// *** Database:    wb_patch_db1
// *** DBTable:     wb_mod_news_layouts
// *** MODIFIED:    Sat, 18 Jul 2020 03:12:20 +0000
// ***************************

if (!\defined('SYSTEM_RUN')) {\header($_SERVER['SERVER_PROTOCOL'].' 404 Not Found'); echo '404 Not Found'; flush(); exit; }


    $aDefault = [
        "id" => 0, // PRIMRAY
        "layout" => "",
        'header' => '',
        'post_loop' => '',
        'footer' => '',
        'post_header' => '',
        'post_footer' => '',
        'comments_header' => '',
        'comments_loop' => '',
        'comments_footer' => '',
        'comments_page' => '',
    ];// end of wb_mod_news_layouts