<?php
// *** autogenerated preset file
// *** Database:    wb_patch_db1
// *** DBTable:     wb_mod_news_settings
// *** MODIFIED:    Sat, 18 Jul 2020 03:12:21 +0000
// ***************************

if (!\defined('SYSTEM_RUN')) {\header($_SERVER['SERVER_PROTOCOL'].' 404 Not Found'); echo '404 Not Found'; flush(); exit; }

    $aDefault = [
        "section_id" => ($section_id ?? 0), // PRIMRAY
        "page_id" => ($page_id ?? 0),
        'header' => '',
        'post_loop' => '',
        'footer' => '',
        "posts_per_page" => 5,
        'post_header' => '',
        'post_footer' => '',
        'comments_header' => '',
        'comments_loop' => '',
        'comments_footer' => '',
        'comments_page' => '',
        "commenting" => "",
        "resize" => 0,
        "use_captcha" => 1,
        "order_field" => "published_when",
        "order" => "DESC",
        "layout" => "default_layout",
        "use_data_protection" => 0,
        "data_protection_link" => 0,
        "layout_id" => 1,
        "id" => 1,
    ];// end of wb_mod_news_settings


